#!/usr/bin/env python
import os
print('''  ___           _        _ _                _          ____ _     _____    _    _   _ 
 |_ _|_ __  ___| |_ __ _| | | ___ _ __     / \        / ___| |   | ____|  / \  | \ | |
  | || '_ \/ __| __/ _` | | |/ _ \ '__|   / _ \ _____| |   | |   |  _|   / _ \ |  \| |
  | || | | \__ \ || (_| | | |  __/ |     / ___ \_____| |___| |___| |___ / ___ \| |\  |
 |___|_| |_|___/\__\__,_|_|_|\___|_|    /_/   \_\     \____|_____|_____/_/   \_\_| \_|

A-CLEAN adalah tool sederhana untuk membersihkan sistem Arch Linux
    ''')
iac = input("Install/Uninstall A-CLEAN i/u/n = ")

if iac == "n":
    cmd = os.system("exit")
elif iac == "i":
    cmd1 = os.system("pacman -S pacman-contrib rmlint ncdu")
    cmd2 = os.system("chmod +x a-clean.py | cp a-clean.py /usr/local/bin/a-clean")
    print("\nA-CLEAN sudah terinstall, gunakan root untuk menjalankan a-clean")
elif iac == "u":
    cmd = os.system("rm /usr/local/bin/a-clean")
